name: Windows Testing

on:
  workflow_dispatch

env:
  php: 8.1

jobs:
 Grunt:
  if: false   #  ye add kar (grunt disable)
  runs-on: windows-latest

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checking out code
        uses: actions/checkout@v4

      - name: Configuring node & npm
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Installing node stuff
        run: npm ci

      - name: Running grunt
        run: npx grunt

      - name: Looking for uncommitted changes
        run: |
          git add .
          git reset -- npm-shrinkwrap.json
          git diff --cached --exit-code

  PHPUnit:
    if: false   #  YE LINE ADD KI (job disable)
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            php: 8.1
            db: pgsql
            extensions: exif, fileinfo, gd, intl, pgsql, mysql, redis, soap, sodium
          - os: windows-latest
            php: 8.0
            db: pgsql
            extensions: exif, fileinfo, gd, intl, pgsql, mysql, redis, soap, sodium

    steps:
      - name: Setting up DB mysql
        if: ${{ matrix.db == 'mysqli' }}
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: 8.0
          user: test
          password: test

      - name: Creating DB mysql
        if: ${{ matrix.db == 'mysqli' }}
        run: mysql --host 127.0.0.1 -utest -ptest -e 'CREATE DATABASE IF NOT EXISTS test COLLATE = utf8mb4_bin;';

      - name: Setting up DB pgsql
        if: ${{ matrix.db == 'pgsql' }}
        run: |
          (Get-Content "$env:PGDATA\postgresql.conf"). `
              replace('#password_encryption = scram-sha-256', 'password_encryption = md5') | `
              Set-Content "$env:PGDATA\postgresql.conf"
          (Get-Content "$env:PGDATA\pg_hba.conf"). `
              replace('scram-sha-256', 'md5') | `
              Set-Content "$env:PGDATA\pg_hba.conf"

      - name: Setting up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2